### ISSUE TITLE
Can't register the hot key

### ISSUE THREAD

**Issue by daruyanagi** [m0ngr31/VirtualDesktopManager#1]
![sshot-213](https://cloud.githubusercontent.com/assets/1104827/13837336/7429ab90-ec4d-11e5-8a26-d3ec98e428ab.png)

Intel HD Graphics Utility may be using Ctrl+Alt+Left/Right.

Windows 10 Pro x64 (Japanese)

**Comment by m0ngr31** [comment]
What does the Intel Utility use the hotkey for? I wonder if you could disable it in the settings?

Either way, this gives me motivation to add support for custom key combos.

**Comment by darthcircuit** [comment]
I think intel uses it for rotating the display

**Comment by daruyanagi** [comment]
We can disable it, and can change key combination, too.

**Comment by rcmero** [comment]
Just a notice that you can't disable the shortcuts through the Intel control panel, but if you right-click on the desktop you can disable them from the "Graphic Options" menu item.

**Comment by m0ngr31** [comment]
I've added checks for this for it to fail a little more graciously, and I've added a settings page where you can use an alternative hotkey (Shift+Alt+Left/Right). I'm planning on adding a custom hotkey selector in the future, but that will be a little more work.
