### ISSUE TITLE
"Virtual Desktop Cycler" application is displayed in Task View

### ISSUE THREAD

**Issue by rcmero** [m0ngr31/VirtualDesktopManager#2]
![captura de ecra 2](https://cloud.githubusercontent.com/assets/5708421/14609682/d951f736-0582-11e6-8d91-9bd651c7d105.png)

If I close this application, it closes VirtualDesktopManager.

**Comment by m0ngr31** [comment]
Okay, I just fixed this in the new release: https://github.com/m0ngr31/VirtualDesktopManager/releases/tag/v1.0.2
