### ISSUE TITLE
Where did the .exe file go? I don't see it in the folder.

### ISSUE THREAD

**Issue by jolson1129** [m0ngr31/VirtualDesktopManager#24]
I downloaded this a few weeks ago and had no problem. I'm confused where the executable went.

Thanks for the useful app.

**Comment by jolson1129** [comment]
Nvmd.

**Comment by Zarvis12** [comment]
hey i tooo have that problem

**Comment by jolson1129** [comment]
Click releases - the correct zips are there.

******************************************
Jacob M Olson PhD
Postdoctoral Associate - Tye Lab
Picower Institute for Learning and Memory
Massachusetts Institute of Technology
jmolson.net
******************************************
