### ISSUE TITLE
I can't find the exe file in your zip file

### ISSUE THREAD

**Issue by Zarvis12** [m0ngr31/VirtualDesktopManager#25]
![image](https://user-images.githubusercontent.com/36318260/36057644-abb43b4a-0e36-11e8-9fa7-86af19a58b00.png)

its not here 

![image](https://user-images.githubusercontent.com/36318260/36057647-c2b668d6-0e36-11e8-96d2-0c59f7da9ead.png)

it's not here too...

![image](https://user-images.githubusercontent.com/36318260/36057656-d9b7f4d2-0e36-11e8-99d0-375c22353ac7.png)

it's not here too 

if this exe if=s found by anyone please help me

**Comment by UndarkAido** [comment]
https://github.com/m0ngr31/VirtualDesktopManager/releases
