### ISSUE TITLE
Unable to get working since Windows 10 anniversary update

### ISSUE THREAD

**Issue by kkuhle** [m0ngr31/VirtualDesktopManager#4]
When I load the application and mouse over it, the icon goes away and there doesn't seem to be a process for it.

**Comment by Galixte** [comment]
Hi @m0ngr31,

could you take a look, please ?

**Comment by Aleksanderis** [comment]
The error actually comes from third-party library - https://github.com/Grabacr07/VirtualDesktop
There is a newer version of this library in Nuget. I tried to update the package and recompiled VirtualDesktopManager - and now it works. Although this newer version of VirtualDesktop package is still in beta.

**Comment by kkuhle** [comment]
Thanks for the update Aleksanderis.  Is there somewhere that we can get this version and try it out?

**Comment by Aleksanderis** [comment]
I could do a pull request with the fix, but I'm not sure about it, since it relays on beta version of mentioned third-party library - so it should be decide by the owner.

Actually, it's quite an easy fix if you can compile it yourself, since it's quite small and trivial application. If you are not a developer and don't have Visual Studio - then it's not so trivial.

**Comment by m0ngr31** [comment]
I'm actually running Linux full time right now, but I'll spin up a VM and recompile it soon. Sorry about the troubles. The library I'm using is kind of a reverse-engineered API since MS hasn't opened up virtual desktops at all.

**Comment by kkuhle** [comment]
Thanks @m0ngr31 it would be really nice to have the functionality of this app back if you get a chance to look at it.

**Comment by m0ngr31** [comment]
Had to boot up a VM on Azure, but I got it re-compiled. Let me know if it works now.

**Comment by kkuhle** [comment]
I've downloaded version 1.6.0 on the releases page.  It says it was released in April, but it is the latest available version.  Do you have that somewhere else that I am missing to get the re-compiled version?

**Comment by m0ngr31** [comment]
The code itself is the same, it's just that there is an updated library that needed to be updated and recompiled.

**Comment by thany** [comment]
For those unable to recompile stuff themselves, can you make an updated release, if you'd be so kind?

**Comment by m0ngr31** [comment]
1.6 is the updated version even though the source hasn't changed. The only thing that needed updating was one of the libraries it depended on.

**Comment by thany** [comment]
Okay fair enough. But sorry to say it still crashes, and in the same manner as well.

**Comment by vivlim** [comment]
@thany @kkuhle, you can try my build I link to in #7, and see if that helps

**Comment by m0ngr31** [comment]
@mjlim Thanks for the PR. I recompiled it on my Azure VM. Should be good on the new release download.

**Comment by kkuhle** [comment]
Newest package working for me.  Thanks for getting that working again!
