### ISSUE TITLE
Feature Request: Total number of open desktops/List of open desktops on left click

### ISSUE THREAD

**Issue by sarah-noor-12232** [m0ngr31/VirtualDesktopManager#44]
Mainly I installed this so I don't have any forgotten open desktops. It would be neat if the tool can display how many desktops are open.
It wouldn't be feasible to display within icon, but could be displayed upon left clicking the icon.

Upon left clicking taskbar icon, it could display **a list of open desktops** too.

**Comment by iskmz** [comment]
my fork has these features ...
you can remove/hide any extra features of course ... 

[https://github.com/iskmz/VirtualDesktopManager](https://github.com/iskmz/VirtualDesktopManager)

**Comment by sarah-noor-12232** [comment]
> my fork has these features ... you can remove/hide any extra features of course ...
> 
> https://github.com/iskmz/VirtualDesktopManager

Well this is awesome, it also cycles instantaneously compared to touchpad gestures. Thanks!
