### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by thany** [m0ngr31/VirtualDesktopManager#5]
When I start the program, it crashes immedaitely. Every time. I get the friendly "VirtualDesktopCycle has stopped working" dialog coming up, and nothing else. I can't find if there's any logging going on, or how else to supply more information.

All my software is currently at their latest versions. Everything is up-to-date.

**Comment by m0ngr31** [comment]
Had to boot up a VM on Azure, but I got it re-compiled. Let me know if it works now.
