### ISSUE TITLE
No more run on Windows 10 R2

### ISSUE THREAD

**Issue by behel33** [m0ngr31/VirtualDesktopManager#6]
Since I has update Windows 10 to R2 (this summer), virtualDestopManager no more running.
I d'ont have any error.

**Comment by joncox123** [comment]
It also terminates without error on Windows 10 Pro 64-bit Version 1607 (OS Build 14393.187). This is the latest update as of this posting. This is USA English version, as well.

**Comment by m0ngr31** [comment]
Okay, I had a misunderstanding of what the solution was. Try the newest release.

**Comment by behel33** [comment]
Tank you of your response
